import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";

async function signedIn(){const u=await getChatGPTUser();if(!u)return null;await env.DB.prepare("INSERT INTO users(id,email,name) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name").bind(u.userId,u.email,u.fullName).run();return u}

export async function GET(){const u=await signedIn();if(!u)return Response.json({error:"Sign in required"},{status:401});const [lists,plans,tests,notices,bookmarks,progress]=await Promise.all([
  env.DB.prepare("SELECT l.*,COUNT(i.question_id) itemCount FROM personal_lists l LEFT JOIN personal_list_items i ON i.list_id=l.id WHERE l.user_id=? GROUP BY l.id ORDER BY l.created_at DESC").bind(u.userId).all(),
  env.DB.prepare("SELECT p.*,s.name subject,(SELECT COUNT(*) FROM study_plan_items i WHERE i.plan_id=p.id) itemCount FROM study_plans p JOIN subjects s ON s.id=p.subject_id WHERE p.user_id=? ORDER BY p.exam_date").bind(u.userId).all(),
  env.DB.prepare("SELECT m.*,s.name subject FROM mock_tests m JOIN subjects s ON s.id=m.subject_id WHERE m.user_id=? ORDER BY m.created_at DESC LIMIT 10").bind(u.userId).all(),
  env.DB.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 20").bind(u.userId).all(),
  env.DB.prepare("SELECT COUNT(*) count FROM bookmarks WHERE user_id=?").bind(u.userId).first(),env.DB.prepare("SELECT status,COUNT(*) count FROM preparation WHERE user_id=? GROUP BY status").bind(u.userId).all()]);
  return Response.json({lists:lists.results,plans:plans.results,tests:tests.results,notifications:notices.results,bookmarkCount:(bookmarks as {count?:number})?.count??0,progress:progress.results});}

export async function POST(request:Request){const u=await signedIn();if(!u)return Response.json({error:"Sign in required"},{status:401});const p=await request.json() as Record<string,unknown>;const action=String(p.action||"");
  if(action==="createList"){const name=String(p.name||"").trim();if(!name)return Response.json({error:"Name required"},{status:400});const row=await env.DB.prepare("INSERT INTO personal_lists(user_id,name) VALUES(?,?) RETURNING *").bind(u.userId,name).first();return Response.json({list:row},{status:201})}
  if(action==="addToList"){await env.DB.prepare("INSERT OR IGNORE INTO personal_list_items(list_id,question_id,position) SELECT id,?,(SELECT COUNT(*) FROM personal_list_items WHERE list_id=?) FROM personal_lists WHERE id=? AND user_id=?").bind(Number(p.questionId),Number(p.listId),Number(p.listId),u.userId).run();return Response.json({saved:true})}
  if(action==="createPlan"){const subjectId=Number(p.subjectId),examDate=String(p.examDate||""),minutes=Math.max(15,Number(p.dailyMinutes)||120);if(!subjectId||!/^\d{4}-\d{2}-\d{2}$/.test(examDate))return Response.json({error:"Valid subject and exam date required"},{status:400});const plan=await env.DB.prepare("INSERT INTO study_plans(user_id,subject_id,exam_date,daily_minutes) VALUES(?,?,?,?) RETURNING id").bind(u.userId,subjectId,examDate,minutes).first<{id:number}>();const topics=await env.DB.prepare("SELECT id,name FROM topics WHERE subject_id=? ORDER BY id").bind(subjectId).all<{id:number,name:string}>();const start=new Date();const statements=topics.results.map((t,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return env.DB.prepare("INSERT INTO study_plan_items(plan_id,topic_id,scheduled_date,title,kind) VALUES(?,?,?,?,?)").bind(plan!.id,t.id,d.toISOString().slice(0,10),t.name,"study")});const testDay=new Date(start);testDay.setDate(testDay.getDate()+topics.results.length);statements.push(env.DB.prepare("INSERT INTO study_plan_items(plan_id,scheduled_date,title,kind) VALUES(?,?,?,?)").bind(plan!.id,testDay.toISOString().slice(0,10),"Final mock test","mock"));statements.push(env.DB.prepare("INSERT INTO notifications(user_id,type,title,body) VALUES(?,?,?,?)").bind(u.userId,"plan","Study plan ready",`Your ${topics.results.length+1}-day plan has been generated.`));await env.DB.batch(statements);return Response.json({planId:plan!.id},{status:201})}
  if(action==="createMock"){const subjectId=Number(p.subjectId),count=Math.min(20,Math.max(5,Number(p.count)||10)),duration=Math.max(10,Number(p.duration)||20);const test=await env.DB.prepare("INSERT INTO mock_tests(user_id,subject_id,title,duration_minutes,total) SELECT ?,id,name||' Practice Test',?,? FROM subjects WHERE id=? RETURNING id").bind(u.userId,duration,count,subjectId).first<{id:number}>();if(!test)return Response.json({error:"Subject not found"},{status:404});await env.DB.batch([env.DB.prepare("INSERT INTO mock_test_questions(test_id,question_id,position) SELECT ?,id,ROW_NUMBER() OVER(ORDER BY importance_score DESC) FROM questions WHERE subject_id=? ORDER BY importance_score DESC LIMIT ?").bind(test.id,subjectId,count),env.DB.prepare("INSERT INTO notifications(user_id,type,title,body) VALUES(?,?,?,?)").bind(u.userId,"mock","Mock test created",`${count} questions · ${duration} minutes`)]);return Response.json({testId:test.id},{status:201})}
  if(action==="report"){await env.DB.prepare("INSERT INTO reports(user_id,question_id,type,details) VALUES(?,?,?,?)").bind(u.userId,Number(p.questionId)||null,String(p.type||"Other"),String(p.details||"")).run();return Response.json({reported:true})}
  if(action==="readNotification"){await env.DB.prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").bind(Number(p.id),u.userId).run();return Response.json({updated:true})}
  return Response.json({error:"Unknown action"},{status:400});}
