"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Catalog = { subjects: {id:number;name:string;code:string}[]; colleges:{id:number;name:string}[]; examTypes:string[]; years:number[] };
type Question = { id:number;text:string;easyAnswer:string;examAnswer:string;marks:number;importanceScore:number;subject:string;code:string;topic:string;repeatCount:number;years:string };

export default function QuestionExplorer() {
  const [catalog,setCatalog]=useState<Catalog|null>(null), [questions,setQuestions]=useState<Question[]>([]), [loading,setLoading]=useState(true);
  const [q,setQ]=useState(""), [subject,setSubject]=useState(""), [year,setYear]=useState(""), [examType,setExamType]=useState(""), [importance,setImportance]=useState("");
  const [answer,setAnswer]=useState<{id:number;mode:"easy"|"exam"}|null>(null), [message,setMessage]=useState("");
  useEffect(()=>{fetch("/api/catalog").then(r=>r.json()).then(setCatalog)},[]);
  const load=useCallback(async()=>{setLoading(true);const p=new URLSearchParams();if(q)p.set("q",q);if(subject)p.set("subject",subject);if(year)p.set("year",year);if(examType)p.set("examType",examType);if(importance)p.set("importance",importance);const r=await fetch(`/api/questions?${p}`);const data=await r.json();setQuestions(data.questions??[]);setLoading(false)},[q,subject,year,examType,importance]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
  const counts=useMemo(()=>({high:questions.filter(x=>x.importanceScore>=90).length,total:questions.length}),[questions]);
  async function bookmark(id:number){const r=await fetch("/api/bookmarks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:id})});if(r.status===401){location.href="/signin-with-chatgpt?return_to=%2Fquestions";return}setMessage(r.ok?"Saved to Must Study":"Could not save");setTimeout(()=>setMessage(""),2200)}
  async function progress(id:number,status:string){const r=await fetch("/api/progress",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:id,status})});if(r.status===401){location.href="/signin-with-chatgpt?return_to=%2Fquestions";return}setMessage("Preparation status updated");setTimeout(()=>setMessage(""),2200)}
  return <main className="qb-shell">
    <header className="qb-top"><a href="/" className="brand"><span className="brand-mark">S</span><span>Sohoj<span>Exam</span></span></a><nav><a href="/">Home</a><a className="active" href="/questions">Extracted Questions</a><a href="/explore">Question Papers</a><a href="/dashboard">Dashboard</a></nav><a className="qb-sign" href="/signin-with-chatgpt?return_to=%2Fquestions">Sign in</a></header>
    <a className="paper-library-banner" href="/explore"><span>PDF</span><div><b>Looking for complete semester question papers?</b><small>Browse 2020-2023 Final papers by semester and subject</small></div><strong>Open Question Papers →</strong></a>
    <section className="qb-hero"><div><span>VERIFIED PREVIOUS QUESTIONS</span><h1>Find the questions that<br/><em>matter most.</em></h1><p>Search, filter, understand and track your preparation from one focused workspace.</p></div><aside><b>{counts.total}</b><span>matching questions</span><i>{counts.high} very important</i></aside></section>
    <section className="qb-body"><aside className="filter-panel"><div className="filter-head"><b>Filters</b><button onClick={()=>{setSubject("");setYear("");setExamType("");setImportance("")}}>Reset</button></div><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}><option value="">All subjects</option>{(catalog?.subjects??[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Exam type<select value={examType} onChange={e=>setExamType(e.target.value)}><option value="">All exam types</option>{(catalog?.examTypes??[]).map(x=><option key={x}>{x}</option>)}</select></label><label>Year<select value={year} onChange={e=>setYear(e.target.value)}><option value="">All years</option>{(catalog?.years??[]).map(x=><option key={x}>{x}</option>)}</select></label><label>Importance<select value={importance} onChange={e=>setImportance(e.target.value)}><option value="">All priorities</option><option value="90">Very Important</option><option value="80">Important</option><option value="60">Medium</option></select></label><div className="filter-note"><span>✦</span><b>Smart ranking</b><p>Scores combine repetition, recency, coverage and expert priority.</p></div></aside>
      <div className="qb-results"><div className="qb-search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search question, topic or subject code..."/><button onClick={load}>Search</button></div><div className="result-bar"><b>{loading?"Finding questions...":`${questions.length} questions found`}</b><span>Sorted by importance</span></div>
        {!loading&&questions.map(x=><article className="qb-card" key={x.id}><div className="score-badge"><b>{x.importanceScore}</b><span>SCORE</span></div><div className="qb-main"><div className="qb-tags"><span className={x.importanceScore>=90?"red":"orange"}>{x.importanceScore>=90?"Very Important":"Important"}</span><span>{x.topic}</span><span>{x.marks} marks</span></div><h2>{x.text}</h2><div className="qb-meta"><span><b>{x.repeatCount}×</b> repeated</span><span>{x.subject} · {x.code}</span><span>{x.years?.split(",").sort().join(", ")}</span></div>{answer?.id===x.id&&<div className="answer-box"><div><button className={answer.mode==="easy"?"active":""} onClick={()=>setAnswer({id:x.id,mode:"easy"})}>সহজ ব্যাখ্যা</button><button className={answer.mode==="exam"?"active":""} onClick={()=>setAnswer({id:x.id,mode:"exam"})}>Exam answer</button></div><p>{answer.mode==="easy"?x.easyAnswer:x.examAnswer}</p></div>}<div className="qb-actions"><button onClick={()=>setAnswer(answer?.id===x.id?null:{id:x.id,mode:"easy"})}>{answer?.id===x.id?"Hide answer":"Show answer"}</button><button onClick={()=>bookmark(x.id)}>♡ Bookmark</button><select defaultValue="" onChange={e=>progress(x.id,e.target.value)} aria-label="Preparation status"><option value="" disabled>Set status</option><option value="learning">Learning</option><option value="completed">Completed</option><option value="revision">Need revision</option></select></div></div></article>)}
        {!loading&&!questions.length&&<div className="empty-state"><span>⌕</span><h3>No matching questions</h3><p>Try clearing a filter or using a broader search.</p></div>}
      </div></section>{message&&<div className="toast">✓ {message}</div>}
  </main>
}
