"use client";
import { useEffect, useMemo, useState } from "react";
import { staticPapers } from "../../lib/paper-catalog";
import { MobilePapers } from "../mobile/mobile-papers";

type Catalog={departments:{id:number;name:string;code:string;active:boolean}[];semesters:{id:number;departmentId:number;name:string;position:number}[];subjects:{id:number;semesterId:number;name:string;code:string}[];colleges:{id:number;name:string}[];examTypes:string[];years:number[]};
type Paper={id:number;title:string;subject:string;startPage:number;endPage:number;pdfId?:number;asset?:string;slug?:string};

const fallbackCatalog:Catalog={departments:[{id:1,name:"Computer Science & Engineering",code:"CSE",active:true}],semesters:[{id:3,departmentId:1,name:"2nd Year 1st Semester",position:3}],subjects:[{id:301,semesterId:3,name:"Object Oriented Programming Language",code:"CSE-301"},{id:303,semesterId:3,name:"Data Structure",code:"CSE-303"},{id:401,semesterId:3,name:"Data Structure and Algorithm (DSA)",code:"CSE-401"},{id:402,semesterId:3,name:"Linear Algebra",code:"MATH-401"},{id:407,semesterId:3,name:"Electrical Devices and Instrumentation",code:"EEE-407"},{id:403,semesterId:3,name:"Digital Electronics & Pulse Technique",code:"CSE-403"}],colleges:[],examTypes:["Final"],years:[2023,2022,2021,2020]};
const subjectIds:Record<string,number>={"CSE-301":301,"CSE-303":303,"CSE-401":401,"MATH-401":402,"EEE-407":407,"CSE-403":403};
const fallbackPapers:Paper[]=staticPapers.map(p=>({id:Number(`${p.year}${subjectIds[p.code]}`),title:`${p.subject} - ${p.title}`,subject:p.subject,startPage:1,endPage:p.pages,slug:p.slug,asset:`/papers/${p.slug}`}));

export default function Explore(){
 const[c,setC]=useState<Catalog>(fallbackCatalog),[dep,setDep]=useState(1),[sem,setSem]=useState(3),[sub,setSub]=useState(301),[exam,setExam]=useState("Final"),[year,setYear]=useState(2023),[college,setCollege]=useState(0),[papers,setPapers]=useState<Paper[]>(fallbackPapers.filter(x=>x.id===2023301));
 useEffect(()=>{fetch("/api/catalog").then(r=>r.json()).then((data:Catalog)=>{if(data?.subjects?.length){setC(data);const requested=new URLSearchParams(location.search).get("subject");const target=data.subjects.find(x=>x.code===requested)??data.subjects.find(x=>x.code==="CSE-301")??data.subjects[0];setSub(target.id);setSem(target.semesterId)}}).catch(()=>setC(fallbackCatalog))},[]);
 const semesters=useMemo(()=>c.semesters.filter(x=>x.departmentId===dep),[c,dep]);
 const subjects=useMemo(()=>c.subjects.filter(x=>x.semesterId===sem),[c,sem]);
 useEffect(()=>{const selectedCode=c.subjects.find(x=>x.id===sub)?.code;const local=exam==="Final"?fallbackPapers.filter(x=>x.id===Number(`${year}${subjectIds[selectedCode??""]}`)):[];const p=new URLSearchParams({subject:String(sub),year:String(year),examType:exam});if(college)p.set("college",String(college));fetch(`/api/papers?${p}`).then(r=>r.json()).then(d=>setPapers(d.papers?.length?d.papers:local)).catch(()=>setPapers(local))},[c,sub,year,exam,college]);
 const selected=subjects.find(x=>x.id===sub);
 useEffect(()=>{const card=document.querySelector<HTMLElement>(".subject-overview");if(!card)return;const paper=papers[0],href=paper?(paper.asset?`${paper.asset}#page=${paper.startPage}`:`/pdf/${paper.pdfId}?start=${paper.startPage}&end=${paper.endPage}`):"";card.classList.toggle("paper-ready",Boolean(href));card.tabIndex=href?0:-1;card.setAttribute("role",href?"link":"status");const open=()=>{if(href)location.href=href};const click=()=>open(),key=(event:KeyboardEvent)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();open()}};card.addEventListener("click",click);card.addEventListener("keydown",key);return()=>{card.removeEventListener("click",click);card.removeEventListener("keydown",key)}},[papers]);
 return <main className="explore-page"><MobilePapers/><header><a href="/" className="brand"><span className="brand-mark">S</span><span>Sohoj<span>Exam</span></span></a><nav><a href="/questions">Extracted Questions</a><a className="active" href="/explore">Question Papers</a><a href="/dashboard">Dashboard</a></nav></header><section className="explore-hero"><span>ACADEMIC LIBRARY</span><h1>Find complete question papers</h1><p>Choose a subject and year, then tap the selected subject card to open its question paper.</p></section><section className="path-panel"><div className="path-title"><b>Your path</b><span>CSE / {semesters.find(x=>x.id===sem)?.name} / {selected?.name}</span></div><div className="path-grid"><label>Department<select value={dep} onChange={e=>setDep(Number(e.target.value))}>{c.departments.map(x=><option key={x.id} value={x.id} disabled={!x.active}>{x.code}{!x.active?" / Coming soon":""}</option>)}</select></label><label>Semester<select value={sem} onChange={e=>{const value=Number(e.target.value);setSem(value);setSub(c.subjects.find(x=>x.semesterId===value)?.id??0)}}>{semesters.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Subject<select value={sub} onChange={e=>setSub(Number(e.target.value))}>{subjects.map(x=><option key={x.id} value={x.id}>{x.code} / {x.name}</option>)}</select></label><label>Exam type<select value={exam} onChange={e=>setExam(e.target.value)}>{c.examTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Year<select value={year} onChange={e=>setYear(Number(e.target.value))}>{c.years.map(x=><option key={x}>{x}</option>)}</select></label>{exam!=="Final"&&<label>College<select value={college} onChange={e=>setCollege(Number(e.target.value))}><option value="0">All colleges</option>{c.colleges.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>}</div></section><section className="subject-overview"><div><span>SELECTED SUBJECT</span><h2>{selected?.name||"Choose a subject"}</h2><p>{selected?.code}</p></div><aside><b>{papers.length}</b><span>question paper found</span></aside></section><section className="paper-list"><div><h2>Available question papers</h2><span>{year} / {exam}</span></div>{papers.length?papers.map(p=><article key={String(p.id)}><span>PDF</span><p><b>{p.title}</b><small>{p.subject} / University final / Pages {p.startPage} to {p.endPage}</small></p><div className="paper-actions"><a href={p.asset?`${p.asset}#page=${p.startPage}`:`/pdf/${p.pdfId}?start=${p.startPage}&end=${p.endPage}`}>View PDF</a><a className="download" href={p.asset??`/api/pdfs/${p.pdfId}?start=${p.startPage}&end=${p.endPage}&download=1`} download>Download</a></div></article>):<div className="no-papers"><span>PDF</span><h3>No mapped paper yet</h3><p>Try another subject, exam type or year.</p></div>}</section></main>
}
