import { desc, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { questions, users } from "../../../../db/schema";
import { getChatGPTUser } from "../../../chatgpt-auth";

async function admin() { const identity=await getChatGPTUser(); if(!identity)return null; const [user]=await getDb().select().from(users).where(eq(users.id,identity.userId)).limit(1); return user?.role==="admin"?identity:null; }
export async function GET(){if(!await admin())return Response.json({error:"Admin access required"},{status:403});return Response.json({questions:await getDb().select().from(questions).orderBy(desc(questions.updatedAt)).limit(100)});}
export async function POST(request:Request){if(!await admin())return Response.json({error:"Admin access required"},{status:403});const p=await request.json() as {subjectId?:number;topicId?:number;text?:string;easyAnswer?:string;examAnswer?:string;marks?:number;importanceScore?:number};if(!p.subjectId||!p.text?.trim())return Response.json({error:"Subject and question are required"},{status:400});const [row]=await getDb().insert(questions).values({subjectId:p.subjectId,topicId:p.topicId||null,text:p.text.trim(),easyAnswer:p.easyAnswer?.trim()||"",examAnswer:p.examAnswer?.trim()||"",marks:p.marks||0,importanceScore:Math.min(100,Math.max(0,p.importanceScore||0))}).returning();return Response.json({question:row},{status:201});}
export async function PATCH(request:Request){if(!await admin())return Response.json({error:"Admin access required"},{status:403});const p=await request.json() as {id?:number;text?:string;easyAnswer?:string;examAnswer?:string;marks?:number;importanceScore?:number};if(!p.id)return Response.json({error:"Question ID required"},{status:400});await getDb().update(questions).set({text:p.text?.trim(),easyAnswer:p.easyAnswer?.trim(),examAnswer:p.examAnswer?.trim(),marks:p.marks,importanceScore:p.importanceScore,updatedAt:new Date().toISOString()}).where(eq(questions.id,p.id));return Response.json({updated:true});}
export async function DELETE(request:Request){if(!await admin())return Response.json({error:"Admin access required"},{status:403});const id=Number(new URL(request.url).searchParams.get("id"));if(!id)return Response.json({error:"Question ID required"},{status:400});await getDb().delete(questions).where(eq(questions.id,id));return Response.json({deleted:true});}
