import { eq, sql } from "drizzle-orm";
import { getDb } from "../../db";
import { bookmarks, preparation, questions, subjects, users } from "../../db/schema";
import { chatGPTSignOutPath, requireChatGPTUser } from "../chatgpt-auth";
export const dynamic = "force-dynamic";
type Recommendation={id:number;text:string;subject:string;score:number};
function DashboardView({name,saved,completed,recent,guest=false}:{name:string;saved:number;completed:number;recent:Recommendation[];guest?:boolean}){return <main className="student-dash"><aside><a href="/" className="brand"><span className="brand-mark">S</span><span>Sohoj<span>Exam</span></span></a><nav><a className="active" href="/dashboard">⌂ Overview</a><a href="/questions">⌕ Question Bank</a><a href="/explore">▣ Question Papers</a><a href="/workspace">✦ Study Planner</a></nav>{guest?<a className="signout" href="/questions">Start studying</a>:<a className="signout" href={chatGPTSignOutPath("/")}>Sign out</a>}</aside><section><header><div><small>STUDENT WORKSPACE</small><h1>Welcome, {name}</h1><p>{guest?"Your preparation dashboard is ready. Sign-in features will activate when public authentication is connected.":"Stay focused - your next exam is getting closer."}</p></div><span className="dash-avatar">{name.slice(0,2).toUpperCase()}</span></header>{guest&&<div className="dashboard-notice"><b>Guest dashboard</b><span>You can browse all question papers now. Personal bookmarks and progress require sign-in.</span></div>}<div className="dash-stats"><article><span>♡</span><div><b>{saved}</b><small>Saved questions</small></div></article><article><span>✓</span><div><b>{completed}</b><small>Completed</small></div></article><article><span>▣</span><div><b>20</b><small>Question papers</small></div></article><article><span>◷</span><div><b>4</b><small>Available years</small></div></article></div><div className="dashboard-grid"><article className="next-exam"><span>QUESTION LIBRARY</span><h2>2nd Year 1st Semester</h2><p>Final papers from 2020, 2021, 2022 and 2023</p><div><i style={{width:"100%"}}/></div><small>Subject-specific PDF viewers are ready</small><a href="/explore">Browse question papers →</a></article><article className="daily-goal"><span>QUICK START</span><div className="goal-ring"><b>20</b><small>papers</small></div><p>Select a subject and start preparing.</p></article></div><div className="recommended"><div><h2>Recommended subjects</h2><a href="/explore">View all →</a></div>{recent.map((x,i)=><a href="/explore" key={x.id}><span>0{i+1}</span><p><b>{x.text}</b><small>{x.subject}</small></p><strong>{x.score}</strong></a>)}</div></section></main>}
const guestRecommendations:Recommendation[]=[{id:1,text:"Data Structure and Algorithm (DSA)",subject:"CSE-401 · 2023 Final",score:96},{id:2,text:"Object Oriented Programming Language",subject:"CSE-301 · 2023 Final",score:92},{id:3,text:"Linear Algebra",subject:"MATH-401 · 2023 Final",score:88},{id:4,text:"Electrical Devices and Instrumentation",subject:"EEE-407 · 2023 Final",score:84}];
export default async function Dashboard(){if(process.env.VERCEL==="1")return <DashboardView name="Student" saved={0} completed={0} recent={guestRecommendations} guest/>;const identity=await requireChatGPTUser("/dashboard"),db=getDb();await db.insert(users).values({id:identity.userId,email:identity.email,name:identity.fullName}).onConflictDoUpdate({target:users.id,set:{email:identity.email,name:identity.fullName}});const[saved,completed,recent]=await Promise.all([db.select({count:sql<number>`count(*)`}).from(bookmarks).where(eq(bookmarks.userId,identity.userId)),db.select({count:sql<number>`count(*)`}).from(preparation).where(sql`${preparation.userId}=${identity.userId} AND ${preparation.status}='completed'`),db.select({id:questions.id,text:questions.text,subject:subjects.name,score:questions.importanceScore}).from(questions).innerJoin(subjects,eq(questions.subjectId,subjects.id)).orderBy(sql`${questions.importanceScore} DESC`).limit(4)]);return <DashboardView name={identity.displayName.split(" ")[0]} saved={saved[0]?.count??0} completed={completed[0]?.count??0} recent={recent}/>}
